#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
PG_BIN="${PG_BIN:-$(brew --prefix postgresql@17)/bin}"
cluster="$(mktemp -d "${TMPDIR:-/tmp}/volta-schema.XXXXXX")"
port="$(python3 - <<'PY'
import socket
with socket.socket() as s:
 s.bind(('127.0.0.1', 0)); print(s.getsockname()[1])
PY
)"
cleanup() { "$PG_BIN/pg_ctl" -D "$cluster/data" -m immediate stop >/dev/null 2>&1 || true; rm -rf "$cluster"; }
trap cleanup EXIT INT TERM
export TESLAMATE_SOURCE="$cluster/teslamate"
git clone --quiet --depth 1 --branch v4.3.0 https://github.com/teslamate-org/teslamate.git "$TESLAMATE_SOURCE"
expected=33d200b2fba9d5138803916a788cef5eae31b1aa
test "$(git -C "$TESLAMATE_SOURCE" rev-parse HEAD)" = "$expected"
"$PG_BIN/initdb" -D "$cluster/data" -A trust --no-instructions >"$cluster/init.log"
"$PG_BIN/pg_ctl" -D "$cluster/data" -l "$cluster/postgres.log" -o "-h 127.0.0.1 -p $port -k $cluster" start >/dev/null
"$PG_BIN/createdb" -h 127.0.0.1 -p "$port" volta_schema
export SCHEMA_DATABASE_URL="postgres://$(id -un)@127.0.0.1:$port/volta_schema"
mix local.hex --force
elixir scripts/schema-migrate.exs >"$cluster/migrations.log" 2>&1 || { tail -30 "$cluster/migrations.log"; exit 1; }
"$PG_BIN/pg_dump" "$SCHEMA_DATABASE_URL" --schema-only --no-owner --no-privileges >"$cluster/schema.sql"
python3 - "$cluster/schema.sql" <<'PY'
import sys
text=open(sys.argv[1]).read()
text='\n'.join(line for line in text.split('\n') if not line.startswith(('\\restrict','\\unrestrict')))
header='-- Generated by executing all unmodified v4.3.0 Ecto migrations.\n-- Upstream commit: 33d200b2fba9d5138803916a788cef5eae31b1aa\n'
open('test/teslamate-v4.3.0.sql','w').write((header+text).rstrip()+'\n')
PY
printf 'Regenerated test/teslamate-v4.3.0.sql from %s\n' "$expected"
